global_costmap:
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 5.0
  static_map: true
  plugins:
    - {name: normalmap,     type: "costmap_2d::StaticLayer"}
    - {name: nogomap,       type: "costmap_2d::StaticLayer"}
    - {name: obstacles,     type: "costmap_2d::ObstacleLayer"}
    - {name: inflations,    type: "costmap_2d::InflationLayer"}
    
  normalmap:
    map_topic: /map
    use_maximum: false
    
  nogomap:
    map_topic: /nogomap/map
    use_maximum: true
    
  obstacles:
    observation_sources: base_scan_front base_scan_rear
    obstacle_range: 2.5
    raytrace_range: 3.0
    
  inflations:
    inflation_radius: 0.25
