map_type: costmap
transform_tolerance: 0.2
obstacle_range: 2.5
raytrace_range: 3.0
inflation_radius: 0.38
footprint: [[0.26, 0.18],
            [0.26, 0.014],
            [0.31, 0.014],
            [0.31, -0.014],
            [0.26, -0.014],
            [0.26, -0.18],
            [-0.27, -0.18],
            [-0.27, 0.18]]

observation_sources: base_scan_front base_scan_rear

base_scan_front: {sensor_frame: hokuyo_front_link,
            data_type: LaserScan,
            topic: /scan_front,
            expected_update_rate: 0.2,
            observation_persistence: 0.0,
            marking: true,
            clearing: true,
            min_obstacle_height: -0.10,
            max_obstacle_height: 2.0}

base_scan_rear: {sensor_frame: hokuyo_back_link,
            data_type: LaserScan,
            topic: /scan_back,
            expected_update_rate: 0.2,
            observation_persistence: 0.0,
            marking: true,
            clearing: true,
            min_obstacle_height: -0.10,
max_obstacle_height: 2.0}

